In [1]:
import os

import polars as pl
import requests
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv('MERAKI_API_KEY')
org_id = "601793500207411081"
network_id = "L_601793500207435626"

/var/folders/ks/3k15nqpj1xl93ys22hqjk47r0000gn/T/ipykernel_42134/3012979541.py:3: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
headers = {
    "X-Cisco-Meraki-API-Key": api_key
}

url = f"https://api.meraki.com/api/v1/networks/{network_id}/clients"
response = requests.get(url, headers=headers, params={
    'perPage': 5000,

})
response.status_code

200

In [3]:
devices = response.json()
devices

[{'id': 'k006cc2',
  'mac': '42:42:3e:48:0e:73',
  'description': 'Allans-iPhone-Work',
  'ip': '172.16.1.38',
  'ip6': 'fd9d:3e30:635f:b7e6:101f:24e1:df56:81bd',
  'ip6Local': 'fe80:0:0:0:181d:929b:8df7:1725',
  'user': None,
  'firstSeen': '2023-11-14T19:04:49Z',
  'lastSeen': '2024-02-12T04:30:07Z',
  'manufacturer': None,
  'os': 'Apple iPhone',
  'deviceTypePrediction': 'Apple iPhone 15 Pro, iOS17.1.1',
  'recentDeviceSerial': 'Q3AJ-XPAY-924K',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-2',
  'recentDeviceMac': 'e4:55:a8:80:cf:13',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 73238, 'recv': 203231, 'total': 276469},
  'status': 'Online',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k6497ea',
  'mac': 'b6:b7:fd:bb:20:97',
  'description': 'b68a5fc0-e841-4ac6-8a43-89e9790e89ca',
  'ip': '172.16.1.46',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:44c:d884:6922:2b7a',
  'user': None,
  'firstSeen': '2023-11-20T04:03:31Z',
  'lastSeen': '2024-02-12T02:59:41Z',
  'manufacturer': None,
  'os': 'Apple iPhone',
  'deviceTypePrediction': 'Apple iPhone 15, iOS17.2.1',
  'recentDeviceSerial': 'Q3AJ-WE8B-B3AY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-4',
  'recentDeviceMac': 'e4:55:a8:80:cb:af',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 14457, 'recv': 108078, 'total': 122535},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k6c66b9',
  'mac': 'dc:a6:32:85:c0:ee',
  'description': 'beacon-pi',
  'ip': '172.16.1.24',
  'ip6': 'fd9d:3e30:635f:b7e6:c412:a8c0:d585:f50a',
  'ip6Local': 'fe80:0:0:0:f0d9:b4a2:6909:91d8',
  'user': None,
  'firstSeen': '2023-11-06T22:35:26Z',
  'lastSeen': '2024-02-12T04:29:44Z',
  'manufacturer': 'Raspberry Pi Trading',
  'os': None,
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q3AJ-SXN3-54QG',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-3',
  'recentDeviceMac': 'e4:55:a8:80:cc:7a',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 17, 'recv': 373, 'total': 390},
  'status': 'Online',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ac - 2.4 and 5 GHz'},
 {'id': 'k6ccf55',
  'mac': '52:54:00:74:fb:ea',
  'description': 'Reservations MAC address IP34',
  'ip': '172.16.0.72',
  'ip6': 'fd9d:3e30:635f:b7e6:4389:daac:8ca5:8e29',
  'ip6Local': 'fe80:0:0:0:2236:5e70:55c9:ae28',
  'user': None,
  'firstSeen': '2023-07-10T01:16:27Z',
  'lastSeen': '2024-02-12T04:22:21Z',
  'manufacturer': None,
  'os': None,
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q2YN-TCXP-6DKN',
  'recentDeviceName': 'ZOZO Head Office',
  'recentDeviceMac': 'cc:9c:3e:4f:e5:8c',
  'recentDeviceConnection': 'Wired',
  'ssid': None,
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 190, 'recv': 3876, 'total': 4066},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11b - 2.4 GHz'},
 {'id': 'k6dad4c',
  'mac': '14:7d:da:df:6c:38',
  'description': 'Sophies-MacBook-Pro',
  'ip': '172.16.1.44',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:48c:5902:6764:4125',
  'user': None,
  'firstSeen': '2023-11-19T20:16:06Z',
  'lastSeen': '2024-02-12T02:59:10Z',
  'manufacturer': 'Apple',
  'os': None,
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q3AJ-WE8B-B3AY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-4',
  'recentDeviceMac': 'e4:55:a8:80:cb:af',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 2821, 'recv': 2761, 'total': 5582},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ac - 2.4 and 5 GHz'},
 {'id': 'k7765da',
  'mac': '5c:e9:1e:69:29:72',
  'description': 'Ronalds-MacBook-Pro-M2',
  'ip': '172.16.0.54',
  'ip6': '2407:7000:890a:d700:5a4:94da:c5d4:e078',
  'ip6Local': 'fe80:0:0:0:41:be38:f6f3:886c',
  'user': None,
  'firstSeen': '2023-07-16T19:09:58Z',
  'lastSeen': '2024-02-12T01:06:29Z',
  'manufacturer': 'Apple',
  'os': None,
  'deviceTypePrediction': 'MacBook Pro, macOS14.2.1',
  'recentDeviceSerial': 'Q3AJ-LKG5-97UY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-1',
  'recentDeviceMac': 'e4:55:a8:80:cc:36',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 4847, 'recv': 496038, 'total': 500885},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k77538b',
  'mac': 'de:69:90:63:2d:4c',
  'description': None,
  'ip': '172.16.1.83',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:100f:c222:a17e:36d4',
  'user': None,
  'firstSeen': '2024-01-02T19:09:34Z',
  'lastSeen': '2024-02-12T02:00:58Z',
  'manufacturer': None,
  'os': None,
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q3AL-XV3H-62PX',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR44-2',
  'recentDeviceMac': '0c:7b:c8:a9:4c:3d',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 168, 'recv': 304, 'total': 472},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11n - 2.4 GHz'},
 {'id': 'k7ffeae',
  'mac': '7e:2a:73:83:d9:4f',
  'description': None,
  'ip': '172.16.1.140',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:439:4407:4016:4a34',
  'user': None,
  'firstSeen': '2024-02-11T20:47:22Z',
  'lastSeen': '2024-02-12T02:02:56Z',
  'manufacturer': None,
  'os': None,
  'deviceTypePrediction': 'Apple iPhone 11, iOS16.1',
  'recentDeviceSerial': 'Q3AJ-WE8B-B3AY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-4',
  'recentDeviceMac': 'e4:55:a8:80:cb:af',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 521, 'recv': 1983, 'total': 2504},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k7f3d0e',
  'mac': '5c:e9:1e:6a:33:3e',
  'description': 'Minsuns-MacBook-Pro',
  'ip': '172.16.0.71',
  'ip6': '2406:e001:a:ec00:f8ac:ff35:bf15:9b61',
  'ip6Local': 'fe80:0:0:0:149b:b44c:d50e:a4f6',
  'user': None,
  'firstSeen': '2023-07-16T21:50:16Z',
  'lastSeen': '2024-02-12T04:08:37Z',
  'manufacturer': 'Apple',
  'os': None,
  'deviceTypePrediction': 'MacBook Pro, macOS14.3',
  'recentDeviceSerial': 'Q3AJ-LKG5-97UY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-1',
  'recentDeviceMac': 'e4:55:a8:80:cc:36',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 190707, 'recv': 1511766, 'total': 1702473},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k8095d9',
  'mac': 'c6:c1:24:8b:63:b1',
  'description': 'zgpkdc-13',
  'ip': '172.16.0.179',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:1:8c6c:fa21:efa2',
  'user': None,
  'firstSeen': '2023-08-13T21:22:07Z',
  'lastSeen': '2024-02-12T00:27:29Z',
  'manufacturer': None,
  'os': 'Apple iPhone',
  'deviceTypePrediction': 'Apple iPhone 13 Mini, iOS16.6',
  'recentDeviceSerial': 'Q3AJ-WE8B-B3AY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-4',
  'recentDeviceMac': 'e4:55:a8:80:cb:af',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 17934, 'recv': 1103438, 'total': 1121372},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k811c6e',
  'mac': '2a:92:db:67:32:78',
  'description': 'Android',
  'ip': '172.16.0.139',
  'ip6': 'fd9d:3e30:635f:b7e6:b5f1:1e22:8a9c:b0f1',
  'ip6Local': 'fe80:0:0:0:2892:dbff:fe67:3278',
  'user': None,
  'firstSeen': '2023-07-23T23:31:13Z',
  'lastSeen': '2024-02-12T03:21:50Z',
  'manufacturer': None,
  'os': 'Android',
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q3AJ-WE8B-B3AY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-4',
  'recentDeviceMac': 'e4:55:a8:80:cb:af',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 10196, 'recv': 115342, 'total': 125538},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k82e6b3',
  'mac': '60:3e:5f:35:a1:fb',
  'description': 'Janes-MacBook-Pro',
  'ip': '172.16.1.135',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:1cde:eb9f:dc99:a6fc',
  'user': None,
  'firstSeen': '2024-02-04T20:23:34Z',
  'lastSeen': '2024-02-12T03:34:58Z',
  'manufacturer': 'Apple',
  'os': None,
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q3AJ-LKG5-97UY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-1',
  'recentDeviceMac': 'e4:55:a8:80:cc:36',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 119706, 'recv': 6231484, 'total': 6351190},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k854731',
  'mac': '72:b9:0a:3e:c5:af',
  'description': 'Kayra-Yildizs-iPhone',
  'ip': '172.16.1.122',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:1c73:5714:61db:1a40',
  'user': None,
  'firstSeen': '2024-01-24T20:09:00Z',
  'lastSeen': '2024-02-11T22:54:23Z',
  'manufacturer': None,
  'os': 'Apple iPhone',
  'deviceTypePrediction': 'Apple iPhone 14 Pro, iOS17.2.1',
  'recentDeviceSerial': 'Q3AJ-SXN3-54QG',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-3',
  'recentDeviceMac': 'e4:55:a8:80:cc:7a',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 3071, 'recv': 82372, 'total': 85443},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k8bb15d',
  'mac': '52:54:00:f0:e7:0d',
  'description': 'Reservations MAC address IP29',
  'ip': '172.16.0.38',
  'ip6': 'fd9d:3e30:635f:b7e6:c31b:3792:1930:66af',
  'ip6Local': 'fe80:0:0:0:88fd:dfb1:5422:a75',
  'user': None,
  'firstSeen': '2023-07-13T02:52:55Z',
  'lastSeen': '2024-02-12T04:23:47Z',
  'manufacturer': None,
  'os': None,
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q2YN-TCXP-6DKN',
  'recentDeviceName': 'ZOZO Head Office',
  'recentDeviceMac': 'cc:9c:3e:4f:e5:8c',
  'recentDeviceConnection': 'Wired',
  'ssid': None,
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 356789, 'recv': 7700, 'total': 364489},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11b - 2.4 GHz'},
 {'id': 'k8b2e1d',
  'mac': '7e:2d:8c:9e:9b:7b',
  'description': '18fe7576-e912-4f67-b426-6bc2cd84b874',
  'ip': '172.16.0.251',
  'ip6': 'fd9d:3e30:635f:b7e6:147e:41ed:40b2:5426',
  'ip6Local': 'fe80:0:0:0:1445:de37:c192:ed38',
  'user': None,
  'firstSeen': '2023-10-03T07:01:13Z',
  'lastSeen': '2024-02-12T04:29:56Z',
  'manufacturer': None,
  'os': 'Apple iPhone',
  'deviceTypePrediction': 'Apple iPhone 15 Pro, iOS17.3.1',
  'recentDeviceSerial': 'Q3AJ-LKG5-97UY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-1',
  'recentDeviceMac': 'e4:55:a8:80:cc:36',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 502921, 'recv': 1417986, 'total': 1920908},
  'status': 'Online',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k8cc5b9',
  'mac': 'ee:19:c8:06:00:be',
  'description': None,
  'ip': '172.16.1.90',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:8f0:399b:8450:112d',
  'user': None,
  'firstSeen': '2024-01-07T18:04:27Z',
  'lastSeen': '2024-02-12T02:12:03Z',
  'manufacturer': None,
  'os': None,
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q3AJ-LKG5-97UY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-1',
  'recentDeviceMac': 'e4:55:a8:80:cc:36',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 1903, 'recv': 121675, 'total': 123578},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11n - 2.4 GHz'},
 {'id': 'k8e6ed1',
  'mac': '06:5e:c6:83:68:54',
  'description': 'Android_127857935e1342ea9343998e88dd030c',
  'ip': '172.16.0.76',
  'ip6': 'fd9d:3e30:635f:b7e6:8bf6:b8b:2ad5:f3c7',
  'ip6Local': 'fe80:0:0:0:45e:c6ff:fe83:6854',
  'user': None,
  'firstSeen': '2023-07-16T21:51:17Z',
  'lastSeen': '2024-02-12T03:21:50Z',
  'manufacturer': None,
  'os': 'Android',
  'deviceTypePrediction': 'Galaxy S23 Ultra, Android 14',
  'recentDeviceSerial': 'Q3AJ-WE8B-B3AY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-4',
  'recentDeviceMac': 'e4:55:a8:80:cb:af',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 8769, 'recv': 40679, 'total': 49448},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k8e2133',
  'mac': 'e2:c6:be:a2:46:ab',
  'description': '2bc36c53-9cbf-4ab7-ae6d-57a9c1b9e9b7',
  'ip': '172.16.0.156',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:1c44:2828:3aae:18cc',
  'user': None,
  'firstSeen': '2023-07-30T22:31:14Z',
  'lastSeen': '2024-02-12T02:01:18Z',
  'manufacturer': None,
  'os': None,
  'deviceTypePrediction': 'Apple iPhone 12 Mini, iOS17.2.1',
  'recentDeviceSerial': 'Q3AJ-WE8B-B3AY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-4',
  'recentDeviceMac': 'e4:55:a8:80:cb:af',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 35710, 'recv': 108325, 'total': 144035},
  'status': 'Offline',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k8e3355',
  'mac': 'd8:28:c9:9e:55:ec',
  'description': 'GEModule55EC',
  'ip': '172.16.0.142',
  'ip6': None,
  'ip6Local': None,
  'user': None,
  'firstSeen': '2023-07-24T19:52:41Z',
  'lastSeen': '2024-02-12T04:29:24Z',
  'manufacturer': 'General Electric...',
  'os': 'Eye-Fi Wireless Memory Card',
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q3AL-XV3H-62PX',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR44-2',
  'recentDeviceMac': '0c:7b:c8:a9:4c:3d',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 384, 'recv': 533, 'total': 917},
  'status': 'Online',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11n - 2.4 GHz'},
 {'id': 'k9310ac',
  'mac': '5c:e9:1e:6a:39:a5',
  'description': 'Adams-MacBook-Pro',
  'ip': '172.16.0.88',
  'ip6': '2404:4408:8a57:3f00:6c03:6864:18e3:bb79',
  'ip6Local': 'fe80:0:0:0:1406:837c:bb74:ca87',
  'user': None,
  'firstSeen': '2023-07-16T22:38:17Z',
  'lastSeen': '2024-02-12T04:29:56Z',
  'manufacturer': 'Apple',
  'os': 'Android',
  'deviceTypePrediction': 'MacBook Pro, macOS14.3.1',
  'recentDeviceSerial': 'Q3AJ-LKG5-97UY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-1',
  'recentDeviceMac': 'e4:55:a8:80:cc:36',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 7208, 'recv': 130776, 'total': 137984},
  'status': 'Online',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ax - 2.4 and 5 GHz'},
 {'id': 'k93520b',
  'mac': '5a:5c:c0:4c:db:3b',
  'description': 'Android',
  'ip': '172.16.0.83',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:585c:c0ff:fe4c:db3b',
  'user': None,
  'firstSeen': '2023-07-16T22:01:39Z',
  'lastSeen': '2024-02-12T04:29:56Z',
  'manufacturer': None,
  'os': 'Android',
  'deviceTypePrediction': 'Galaxy A31, Android 12',
  'recentDeviceSerial': 'Q3AJ-LKG5-97UY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-1',
  'recentDeviceMac': 'e4:55:a8:80:cc:36',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 9173, 'recv': 71802, 'total': 80975},
  'status': 'Online',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11ac - 2.4 and 5 GHz'},
 {'id': 'k958822',
  'mac': 'b0:4f:13:de:f4:f1',
  'description': 'Bos-MacBook-Pro-14',
  'ip': '172.16.0.130',
  'ip6': 'fd9d:3e30:635f:b7e6:1081:893b:cf9c:fd',
  'ip6Local': 'fe80:0:0:0:66:21e9:74b2:892c',
  'user': None,
  'firstSeen': '2023-07-23T21:45:49Z',
  'lastSeen': '2024-02-12T04:29:43Z',
  'manufacturer': 'Dell',
  'os': None,
  'deviceTypePrediction': None,
  'recentDeviceSerial': 'Q2YN-TCXP-6DKN',
  'recentDeviceName': 'ZOZO Head Office',
  'recentDeviceMac': 'cc:9c:3e:4f:e5:8c',
  'recentDeviceConnection': 'Wired',
  'ssid': None,
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 148174, 'recv': 250687, 'total': 398861},
  'status': 'Online',
  'notes': None,
  'groupPolicy8021x': None,
  'adaptivePolicyGroup': None,
  'smInstalled': False,
  'namedVlan': None,
  'pskGroup': None,
  'wirelessCapabilities': '802.11b - 2.4 GHz'},
 {'id': 'k9774c1',
  'mac': 'ae:05:be:6c:a8:4b',
  'description': 'Minsun-Stella',
  'ip': '172.16.1.126',
  'ip6': None,
  'ip6Local': 'fe80:0:0:0:8b6:b8ae:52f3:48b5',
  'user': None,
  'firstSeen': '2024-01-29T18:56:48Z',
  'lastSeen': '2024-02-12T04:08:37Z',
  'manufacturer': None,
  'os': 'Apple iPhone',
  'deviceTypePrediction': 'Apple iPhone 15, iOS17.2.1',
  'recentDeviceSerial': 'Q3AJ-WE8B-B3AY',
  'recentDeviceName': 'ZOZO-HAED OFFICE-MR36-4',
  'recentDeviceMac': 'e4:55:a8:80:cb:af',
  'recentDeviceConnection': 'Wireless',
  'ssid': 'ZOZO',
  'vlan': '1',
  'switchport': None,
  'usage': {'sent': 32695, 'recv': 419190, 'total': 451885},
  'status': 'Offline',
  'notes': None,

In [4]:
len(devices)

125

In [11]:
df = pl.DataFrame(devices)
df

shape: (125, 28)
┌─────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ id      ┆ mac        ┆ descriptio ┆ ip        ┆ … ┆ smInstall ┆ namedVlan ┆ pskGroup ┆ wirelessC │
│ ---     ┆ ---        ┆ n          ┆ ---       ┆   ┆ ed        ┆ ---       ┆ ---      ┆ apabiliti │
│ str     ┆ str        ┆ ---        ┆ str       ┆   ┆ ---       ┆ null      ┆ null     ┆ es        │
│         ┆            ┆ str        ┆           ┆   ┆ bool      ┆           ┆          ┆ ---       │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ str       │
╞═════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ k006cc2 ┆ 42:42:3e:4 ┆ Allans-iPh ┆ 172.16.1. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ 8:0e:73    ┆ one-Work   ┆ 38        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k6497ea ┆ b6:b7:fd:b ┆ b68a5fc0-e ┆ 172.16.1. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ b:20:97    ┆ 841-4ac6-8 ┆ 46        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆ a43-89e979 ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│         ┆            ┆ 0e…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ k6c66b9 ┆ dc:a6:32:8 ┆ beacon-pi  ┆ 172.16.1. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ac  │
│         ┆ 5:c0:ee    ┆            ┆ 24        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k6ccf55 ┆ 52:54:00:7 ┆ Reservatio ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11b - │
│         ┆ 4:fb:ea    ┆ ns MAC     ┆ 72        ┆   ┆           ┆           ┆          ┆ 2.4 GHz   │
│         ┆            ┆ address    ┆           ┆   ┆           ┆           ┆          ┆           │
│         ┆            ┆ IP34       ┆           ┆   ┆           ┆           ┆          ┆           │
│ k6dad4c ┆ 14:7d:da:d ┆ Sophies-Ma ┆ 172.16.1. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ac  │
│         ┆ f:6c:38    ┆ cBook-Pro  ┆ 44        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ …       ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ k5cbadb ┆ 9c:b6:d0:f ┆ DESKTOP-K6 ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ac  │
│         ┆ 9:57:cd    ┆ K634S      ┆ 169       ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k5ee41e ┆ 5c:e9:1e:6 ┆ MacBook-Pr ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ a:98:56    ┆ o          ┆ 46        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k6038a7 ┆ 50:84:92:0 ┆ DESKTOP-1H ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ 8:d0:c2    ┆ 8414I      ┆ 55        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k61ce62 ┆ 52:54:00:5 ┆ wei-Standa ┆ 172.16.1. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11b - │
│         ┆ 8:47:0e    ┆ rd-PC-Q35- ┆ 42        ┆   ┆           ┆           ┆          ┆ 2.4 GHz   │
│         ┆            ┆ ICH9-2009  ┆           ┆   ┆           ┆           ┆          ┆           │
│ k63cafc ┆ be:a9:72:2 ┆ null       ┆ 172.16.1. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11n - │
│         ┆ 2:2f:46    ┆            ┆ 82        ┆   ┆           ┆           ┆          ┆ 2.4 and 5 │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ GHz       │
└─────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [23]:
windows_devices = pl.col("os").str.contains("Windows")
mac_devices = pl.col("deviceTypePrediction").str.contains("MacBook")
combined_filter = windows_devices | mac_devices
df_filtered = df.filter(combined_filter)
df_filtered

shape: (27, 28)
┌─────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ id      ┆ mac        ┆ descriptio ┆ ip        ┆ … ┆ smInstall ┆ namedVlan ┆ pskGroup ┆ wirelessC │
│ ---     ┆ ---        ┆ n          ┆ ---       ┆   ┆ ed        ┆ ---       ┆ ---      ┆ apabiliti │
│ str     ┆ str        ┆ ---        ┆ str       ┆   ┆ ---       ┆ null      ┆ null     ┆ es        │
│         ┆            ┆ str        ┆           ┆   ┆ bool      ┆           ┆          ┆ ---       │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ str       │
╞═════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ k7765da ┆ 5c:e9:1e:6 ┆ Ronalds-Ma ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ 9:29:72    ┆ cBook-Pro- ┆ 54        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆ M2         ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k7f3d0e ┆ 5c:e9:1e:6 ┆ Minsuns-Ma ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ a:33:3e    ┆ cBook-Pro  ┆ 71        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k9310ac ┆ 5c:e9:1e:6 ┆ Adams-MacB ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ a:39:a5    ┆ ook-Pro    ┆ 88        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k98156a ┆ 5c:e9:1e:6 ┆ 3f40d2df-0 ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ a:9c:fb    ┆ 2e1-4eaf-8 ┆ 62        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆ b40-37e973 ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│         ┆            ┆ ed…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ ka5a0c9 ┆ f8:4d:89:9 ┆ c9408b96-e ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ 1:02:1e    ┆ 2b2-4b2c-8 ┆ 205       ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆ 05a-0c6601 ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│         ┆            ┆ b0…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ …       ┆ …          ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ k541078 ┆ 08:92:04:7 ┆ DESKTOP-1H ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11b - │
│         ┆ 1:5d:4f    ┆ 8414I      ┆ 116       ┆   ┆           ┆           ┆          ┆ 2.4 GHz   │
│ k5526d9 ┆ bc:d0:74:1 ┆ Jayakandan ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ f:3e:3a    ┆ s-MacBook- ┆ 65        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆ Pro        ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k5cbadb ┆ 9c:b6:d0:f ┆ DESKTOP-K6 ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ac  │
│         ┆ 9:57:cd    ┆ K634S      ┆ 169       ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k5ee41e ┆ 5c:e9:1e:6 ┆ MacBook-Pr ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ a:98:56    ┆ o          ┆ 46        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
│ k6038a7 ┆ 50:84:92:0 ┆ DESKTOP-1H ┆ 172.16.0. ┆ … ┆ false     ┆ null      ┆ null     ┆ 802.11ax  │
│         ┆ 8:d0:c2    ┆ 8414I      ┆ 55        ┆   ┆           ┆           ┆          ┆ - 2.4 and │
│         ┆            ┆            ┆           ┆   ┆           ┆           ┆          ┆ 5 GHz     │
└─────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘